In [1]:
import numpy as np
def min_max(lis):        # to find max,min element in the matrix
  print("maximum and minimum elements in the matrix are ")
  print(np.max(lis))
  print(np.min(lis))
def min_max_in_row(lis,row):#to find max,min element in each row
      print("maximum and minimum elements in the row " )
      print(np.amax(lis,axis=1))
      print(np.amin(lis,axis=1))
def min_max_in_column(lis,col):#to find max,min element in each column
      print("maximum and minimum elements in the column " )
      print(np.amax(lis,axis=0))
      print(np.amin(lis,axis=0))
def trace(lis):
      print("The trace is ")
      if(row!=col):
        print("not possible")
      else:
        sum=0
        for i in range(row):
          for j in range(col):
              if(i==j):
                sum+=lis[i][j]
        print(sum)
def rank(lis):
  print("the rank is")
  print(np.linalg.matrix_rank(lis))
def eigval(lis):
  val,vec =np.linalg.eig(lis)
  print("the eigen values are ",val)
  print("the eigen vectors are ",vec)


lis=[]
row=int(input("Enter number of rows "))
col=int(input("Enter number of columns "))
for i in range(row):
  l=list(map(int,input().strip().split()))  #to store elements in the list
  lis.append(l)

np.array(lis)
min_max(lis)
min_max_in_row(lis,row)
min_max_in_column(lis,col)
trace(lis)
rank(lis)
eigval(lis)

maximum and minimum elements in the matrix are 
9
1
maximum and minimum elements in the column 
[3 6 9]
[1 4 7]
maximum and minimum elements in the column 
[7 8 9]
[1 2 3]
The trace is 
15
the rank is
2
the eigen values are  [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
the eigen vectors are  [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
